-- EarlySnap database schema
-- Apply with: psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f db/schema.sql

CREATE TABLE IF NOT EXISTS users (
    id            BIGSERIAL PRIMARY KEY,
    email         TEXT        NOT NULL UNIQUE,   -- always stored lowercased + trimmed
    password_hash TEXT,                          -- NULL = Google-only account
    name          TEXT,
    google_sub    TEXT UNIQUE,                   -- Google 'sub' claim; NULL = not linked
    google_access_token     TEXT,                -- OAuth access token
    google_refresh_token    TEXT,                -- OAuth refresh token for offline calendar access
    google_token_expires_at TIMESTAMPTZ,         -- Expiration timestamp for access token
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_uploads (
    id                BIGSERIAL PRIMARY KEY,
    uuid              UUID        NOT NULL UNIQUE,
    user_id           BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    filename          TEXT        NOT NULL,         -- stored UUID filename e.g. 550e8400-e29b-41d4-a716-446655440000.jpg
    original_filename TEXT        NOT NULL,         -- original uploaded name
    file_path         TEXT        NOT NULL,         -- relative path e.g. user-uploads/550e8400-e29b-41d4-a716-446655440000.jpg
    file_size         BIGINT      NOT NULL,         -- size in bytes
    mime_type         TEXT        NOT NULL,         -- e.g. image/jpeg, image/png
    source            TEXT        NOT NULL DEFAULT 'camera', -- 'camera' or 'file_input'
    status            TEXT        NOT NULL DEFAULT 'pending', -- 'pending', 'processed', 'error'
    doc_type          TEXT,                          -- e.g. 'bill', 'prescription', 'handwritten_note', 'general'
    extracted_json    JSONB,                         -- structured output from Gemini AI
                                                     -- also holds: plan_snapshots: [{finalised_at, plan_text}, ...] (max 3, newest first)
    suggested_questions JSONB,                        -- top 3 helpful questions generated by AI
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_uploads_user_id ON user_uploads(user_id);
CREATE INDEX IF NOT EXISTS idx_user_uploads_uuid ON user_uploads(uuid);

CREATE TABLE IF NOT EXISTS user_uploads_knowledgebase (
    id             BIGSERIAL   PRIMARY KEY,
    user_upload_id BIGINT      NOT NULL UNIQUE REFERENCES user_uploads(id) ON DELETE CASCADE,
    user_id        BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    summary        TEXT,                                    -- AI-generated summary of document AI chat sessions
    chat_history   JSONB       NOT NULL DEFAULT '[]'::jsonb, -- Full JSON conversation log
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_uploads_kb_upload_id ON user_uploads_knowledgebase(user_upload_id);
CREATE INDEX IF NOT EXISTS idx_user_uploads_kb_user_id ON user_uploads_knowledgebase(user_id);


